title: Nella Balog
theme: stack
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about
      weight: 10
    - identifier: concerts
      name: Concerts
      url: /concerts
      weight: 20
    - identifier: gallery
      name: Gallery
      url: /gallery
      weight: 30
    - identifier: contact
      name: Contact
      url: /contact
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 40

paginate: 10
languages:
    en:
        languageName: English
        title: Nella Balog
        description: Example description
        weight: 1
    hu:
        languageName: Magyar
        title: Balog Nella
        description: Example description
        weight: 2
params:
    mainSections:
        - concerts
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2022
        customText: ""

    dateFormat:
        published: 2006 Jan 02
        lastUpdated: 2006 Jan 02, 15:04 MST

    sidebar:
        compact: true
        emoji:
        subtitle:
        avatar:
            enabled: false
            local: true
            src: img/avatar.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
    widgets:
      homepage:
          - type: search
          - type: archives
            params:
                limit: 5
          - type: categories
            params:
                limit: 10
          - type: tag-cloud
            params:
                limit: 10
      page:
          - type: toc

 #    opengraph:
 #       twitter:
 #           # Your Twitter username
#            site:

            # Available values: summary, summary_large_image
#            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true
