backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "concerts" # Used in routes, e.g., /admin/collections/post
    label: "Concerts" # Used in the UI
    folder: "content/concerts" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Location", name: "location", widget: "map" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Blurb", name: "blurb", widget: "text" }
          - {
              label: "Section",
              name: "section",
              widget: "object",
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "markdown" },
                ],
            }
      - file: "content/about/index.md"
        label: "About"
        name: "about"
        media_folder: ""
        public_folder: ""
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/contact/index.md"
        label: "Contact"
        name: "contact"
        media_folder: ""
        public_folder: ""
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/gallery/index.md"
        label: "Gallery"
        name: "gallery"
        public_folder: ""
        create: true
        fields:
          - { name: 'title', label: 'Title', widget: 'string' }
          - { name: 'description', label: 'Description', widget: 'text' }
          # Layout is needed
          - { name: layout, label: layout, widget: "hidden", default: "gallery"}
          - { name: 'sections', label: 'Sections', widget: 'list', fields: [
              { name: 'title', label: 'Title', widget: 'string' },
              { name: 'images', label: 'Images', widget: 'list', fields: [
                  { name: 'image', label: 'Image', widget: 'image' },
                  { name: 'caption', label: 'Caption', widget: 'string' }
                ]
              }
            ]
          }
