backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "pages"
    label: "EN-Pages"
    files:
      - file: "content/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Blurb", name: "blurb", widget: "text", required: false }
          - {
              label: "menu",
              name: "menu",
              widget: "hidden",
              fields:
                [
                  {
                    label: "main",
                    name: "main",
                    widget: "hidden",
                    fields:
                      [
                        {
                          label: "weight",
                          name: "weight",
                          widget: "hidden",
                          default: "-100",
                        },
                      ],
                  },
                ],
            }
      - file: "content/about/index.md"
        label: "About"
        name: "about"
        media_folder: ""
        public_folder: ""
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/contact/index.md"
        label: "Contact"
        name: "contact"
        media_folder: ""
        public_folder: ""
        fields:
          - { name: type, label: type, widget: "hidden", default: "contact" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/gallery/index.md"
        label: "Gallery"
        name: "gallery"
        public_folder: ""
        create: true
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "description", label: "Description", widget: "text" }
          # Layout is needed
          - { name: type, label: type, widget: "hidden", default: "gallery" }
          - {
              name: "sections",
              label: "Sections",
              widget: "list",
              fields:
                [
                  { name: "title", label: "Title", widget: "string" },
                  {
                    name: "images",
                    label: "Images",
                    widget: "list",
                    fields:
                      [
                        { name: "image", label: "Image", widget: "image" },
                        { name: "caption", label: "Caption", widget: "string" },
                      ],
                  },
                ],
            }
  - name: "concerts" # Used in routes, e.g., /admin/collections/post
    label: "EN-Concerts" # Used in the UI
    folder: "content/concerts" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {
          label: "Save as Draft",
          name: "draft",
          required: false,
          widget: “boolean”,
          default: true,
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Concert date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: false,
        }
      - { label: "Features description", name: "description", widget: "text" }
      - {
          label: "Categories",
          name: "categories",
          widget: "relation",
          collection: "categories",
          search_fields: ["title"],
          value_field: "title",
          display_fields: ["title"],
          required: false,
        }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "categories" # Used in routes, e.g., /admin/collections/post
    label: "EN-Categories" # Used in the UI
    folder: "content/categories" # The path to the folder where the documents are stored
    path: "{{slug}}/_index"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Style",
          name: "style",
          widget: "object",
          fields:
            [
              { name: "Background", label: "background", widget: "color" },
              { name: "Color", label: "color", widget: "color" },
            ],
        }
